# Generated by Django 5.0.2 on 2024-02-21 11:40

import django.db.models.deletion
from django.db import migrations, models




class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=30)),
                ('help_line_no', models.IntegerField()),
                ('industry', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('avg_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('js_id', models.IntegerField(primary_key=True, serialize=False)),
                ('js_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('js_email', models.EmailField(max_length=30)),
                ('mobileno', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobposting',
            fields=[
                ('jp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('vacancies', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('req_qualification', models.CharField(max_length=120)),
                ('req_experience', models.CharField(max_length=40)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('curr_status', models.CharField(default='pending', max_length=40)),
                ('message', models.CharField(max_length=200)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.employer')),
                ('js_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qual_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=40)),
                ('collage', models.CharField(max_length=20)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('js_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.jobseeker')),
            ],
        ),
    ]
