# Generated by Django 5.0.2 on 2024-02-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='js_address',
            field=models.CharField(default='your address', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='jp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='js_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
