# Generated by Django 5.0.2 on 2024-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_jobseeker_js_address_alter_application_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='js_address',
            field=models.TextField(default='your address', max_length=200),
        ),
    ]
