# Generated by Django 5.0.2 on 2024-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_jobseeker_js_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='js_address',
            field=models.CharField(default='your address', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
