# Generated by Django 5.0.2 on 2024-02-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_jobseeker_js_address_alter_jobseeker_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume_addr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
