# Generated by Django 5.0.2 on 2024-02-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_jobseeker_resume_jobseeker_resume_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume_addr',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(default='', upload_to='Resumes/'),
            preserve_default=False,
        ),
    ]
