# Generated by Django 5.0.2 on 2024-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='logindate',
            new_name='logintime',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='logoutdate',
            new_name='logouttime',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
