# Generated by Django 5.0.2 on 2024-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_logindate_login_logintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logouttime',
            field=models.DateTimeField(null=True),
        ),
    ]
