# Generated by Django 5.0.2 on 2024-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_jobseeker_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logouttime',
            field=models.DateTimeField(default=None,null=True),
        ),
    ]
