# Generated by Django 5.0.2 on 2024-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_login_logouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logouttime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
