# Generated by Django 5.0.2 on 2024-03-10 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_alter_login_logouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logintime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
