# Generated by Django 5.0.2 on 2024-03-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_alter_login_logintime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='logouttime',
        ),
    ]
