# Generated by Django 5.0.2 on 2024-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_remove_login_logouttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification',
        ),
        migrations.AddField(
            model_name='qualification',
            name='institute',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='qualification',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='Active', max_length=12),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(upload_to='Resume/'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='end_time',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='start_time',
            field=models.DateField(default=None),
        ),
    ]
