# Generated by Django 5.0.2 on 2024-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_remove_qualification_collage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institute',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='start_time',
            field=models.DateField(),
        ),
    ]
