# Generated by Django 5.0.2 on 2024-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_alter_qualification_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='delete_jobpost',
            field=models.BooleanField(default=0),
        ),
    ]
