# Generated by Django 5.0.2 on 2024-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_jobposting_delete_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='req_experience',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
