# Generated by Django 5.0.2 on 2024-03-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_alter_jobposting_req_experience'),
    ]

    operations = [
    ]
