# Generated by Django 5.0.2 on 2024-03-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_auto_20240313_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='req_experience',
            field=models.CharField(default='fresher', max_length=40),
        ),
    ]
