# Generated by Django 5.0.2 on 2024-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_alter_jobposting_req_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='req_experience',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
