# Generated by Django 5.0.2 on 2024-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_remove_application_emp_id_application_jp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
