# Generated by Django 5.0.2 on 2024-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_alter_application_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
